# Copyright (c) 2026 Martino Pilia
# SPDX-License-Identifier: BSD-3-Clause

load("@cujpegxl_pip//:requirements.bzl", "requirement")
load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ssimulacra2",
    testonly = True,
    srcs = [
        "@libjxl//tools:gauss_blur.cc",
        "@libjxl//tools:no_memory_manager.cc",
        "@libjxl//tools:ssimulacra2.cc",
    ],
    hdrs = [
        "@libjxl//tools:gauss_blur.h",
        "@libjxl//tools:no_memory_manager.h",
        "@libjxl//tools:ssimulacra2.h",
    ],
    deps = [
        "@libjxl//lib:jpegxl",
        "@libjxl//lib:jpegxl_private",
    ],
)

pybind_extension(
    name = "pylibjxl",
    testonly = True,
    srcs = ["pylibjxl.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":ssimulacra2",
        "@libjxl//lib:jpegxl",
        "@libjxl//lib:jpegxl_private",
        "@libjxl//lib:jpegxl_threads",
    ],
)

pybind_extension(
    name = "pynvjpeg",
    testonly = True,
    srcs = ["pynvjpeg.cc"],
    tags = ["gpu"],
    visibility = ["//visibility:public"],
    deps = [
        "@cuda//:cuda_runtime_static",
        "@cuda//:nvjpeg",
    ],
)

py_library(
    name = "quality_benchmark_lib",
    testonly = True,
    srcs = ["quality_benchmark.py"],
    imports = [
        ".",
        "../corpus",
        "../../python",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":pylibjxl",
        ":pynvjpeg",
        "//python:pycujpegxl",
        "//tools/corpus:corpus_prep_lib",
        requirement("numpy"),
        requirement("pillow"),
    ],
)

py_binary(
    name = "quality_benchmark",
    testonly = True,
    srcs = ["quality_benchmark.py"],
    data = ["//data:frames"],
    imports = [
        ".",
        "../corpus",
        "../../python",
    ],
    tags = ["gpu"],
    deps = [":quality_benchmark_lib"],
)

py_test(
    name = "quality_benchmark_test",
    srcs = ["quality_benchmark_test.py"],
    imports = [
        ".",
        "../corpus",
        "../../python",
    ],
    tags = [
        # Transitively imports the pycujpegxl extension
        "no-sanitizers",
    ],
    deps = [
        ":quality_benchmark_lib",
        "//tools/corpus:corpus_prep_lib",
        requirement("numpy"),
        requirement("pillow"),
    ],
)
