# Copyright (c) 2026 Martino Pilia
# SPDX-License-Identifier: BSD-3-Clause

load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "determinism_runner_lib",
    srcs = ["determinism_runner.py"],
    imports = ["."],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "determinism_runner",
    srcs = ["determinism_runner.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "determinism_runner_test",
    srcs = ["determinism_runner_test.py"],
    deps = [":determinism_runner_lib"],
)
