# Copyright (c) 2026 Martino Pilia
# SPDX-License-Identifier: BSD-3-Clause

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "entropy_encoder",
    srcs = ["entropy_encoder.cc"],
    hdrs = ["entropy_encoder.h"],
    testonly = True,
    deps = ["//src/bitstream"],
)

cc_library(
    name = "modular",
    srcs = ["modular.cc"],
    hdrs = ["modular.h"],
    testonly = True,
    deps = [
        ":entropy_encoder",
        "//src:dc_predict",
        "//src/bitstream",
    ],
)

cc_library(
    name = "vardct_frame",
    srcs = ["vardct_frame.cc"],
    hdrs = ["vardct_frame.h"],
    testonly = True,
    deps = [
        ":entropy_encoder",
        ":modular",
        "//src:ac_context",
        "//src:coeff_order",
        "//src:vardct_layout",
        "//src/bitstream",
    ],
)

cc_test(
    name = "entropy_encoder_test",
    srcs = ["entropy_encoder_test.cc"],
    deps = [
        ":entropy_encoder",
        "@libjxl//lib:jpegxl",
        "@libjxl//lib:jpegxl_private",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "modular_test",
    srcs = ["modular_test.cc"],
    deps = [
        ":modular",
        "@libjxl//lib:jpegxl",
        "@libjxl//lib:jpegxl_private",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "vardct_frame_test",
    srcs = ["vardct_frame_test.cc"],
    deps = [
        ":vardct_frame",
        "//src:vardct_layout",
        "@libjxl//lib:jpegxl",
        "@libjxl//lib:jpegxl_private",
        "@googletest//:gtest_main",
    ],
)
