# Copyright (c) 2026 Martino Pilia
# SPDX-License-Identifier: BSD-3-Clause

load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "pkg_mklink", "strip_prefix")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

VERSION = "0.0.0"

SOVERSION = "1"

STAMP = {
    "@SOVERSION@": SOVERSION,
    "@VERSION@": VERSION,
}

expand_template(
    name = "config_cmake",
    out = "cujpegxlConfig.cmake",
    substitutions = STAMP,
    template = "cujpegxlConfig.cmake.in",
)

expand_template(
    name = "config_version_cmake",
    out = "cujpegxlConfigVersion.cmake",
    substitutions = STAMP,
    template = "cujpegxlConfigVersion.cmake.in",
)

expand_template(
    name = "pkgconfig",
    out = "cujpegxl.pc",
    substitutions = STAMP,
    template = "cujpegxl.pc.in",
)

pkg_files(
    name = "pkg_headers",
    srcs = ["//:include/cujpegxl/cujpegxl.h"],
    prefix = "include",
    strip_prefix = strip_prefix.from_pkg("include"),
)

pkg_files(
    name = "pkg_lib",
    srcs = ["//:cujpegxl"],
    prefix = "lib",
    renames = {"//:cujpegxl": "libcujpegxl.so." + SOVERSION},
)

pkg_mklink(
    name = "pkg_lib_symlink",
    link_name = "lib/libcujpegxl.so",
    target = "libcujpegxl.so." + SOVERSION,
)

pkg_files(
    name = "pkg_cmake",
    srcs = [
        ":config_cmake",
        ":config_version_cmake",
    ],
    prefix = "lib/cmake/cujpegxl",
)

pkg_files(
    name = "pkg_pkgconfig",
    srcs = [":pkgconfig"],
    prefix = "lib/pkgconfig",
)

pkg_tar(
    name = "install_tree",
    srcs = [
        ":pkg_cmake",
        ":pkg_headers",
        ":pkg_lib",
        ":pkg_lib_symlink",
        ":pkg_pkgconfig",
    ],
    extension = "tar.gz",
    visibility = ["//visibility:public"],
)
