# Copyright (c) 2026 Martino Pilia
# SPDX-License-Identifier: BSD-3-Clause

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

package(default_visibility = ["//visibility:public"])

RUNTIME_COPTS = [
    "-fno-exceptions",
    "-fno-rtti",
]

cc_library(
    name = "capability",
    srcs = ["capability.cc"],
    hdrs = ["capability.h"],
    copts = RUNTIME_COPTS,
    include_prefix = "cujpegxl",
)

cuda_library(
    name = "capability_cuda",
    srcs = ["capability_cuda.cu"],
    copts = RUNTIME_COPTS,
    deps = [":capability"],
)

cc_library(
    name = "cujpegxl_lib",
    srcs = ["cujpegxl.cc"],
    copts = RUNTIME_COPTS,
    alwayslink = True,
    deps = [
        ":capability",
        ":capability_cuda",
        "//:cujpegxl_headers",
    ],
)

cc_test(
    name = "capability_test",
    srcs = ["capability_test.cc"],
    deps = [
        ":capability",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "query_backend_gpu_test",
    srcs = ["query_backend_gpu_test.cc"],
    tags = [
        "gpu",
        "manual",
    ],
    deps = [
        ":capability",
        ":capability_cuda",
        ":cujpegxl_lib",
        "//:cujpegxl_headers",
        "@googletest//:gtest_main",
    ],
)
